[package]
name = "BuildingBlocks"
version = "0.1.0"
edition = "2021"

[features]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bevy-inspector-egui = "0.22.1"
rand = "0.8.5"
